"""Generate the SQL that rewrites `samples.IPR` / `samples.IPRP` from the sheet.

Before 0.9.0 the IP coordinates were read from the ``RxxPxx`` at the start
of each sample name. Some plates were labelled with the wrong ``RxxPxx``
on their files, so the name is not a reliable source: CORSA ran as IP
run 04, not 02, and PREDICTS P5/P6 are R08P04/P05, not the R08P01/P02
that PCa_Innsbruck also uses. The "Overview of IP runs" sheet is the
source of truth (see [`noxdb.ip_runs`][noxdb.ip_runs]).

Every stored row still carries the old label in its name, and the
sheet's ``Combined*`` column records which plate each old label meant.
This script uses that, once, to find each sample's plate:

1.  The old label (``RxxPxx`` of the name) is looked up in the sheet.
2.  A label that names two plates (``R02P01``, ``R08P01``, ``R08P02``)
    is settled by the sample's projects: the plate whose description
    names one of them wins, and it must be exactly one.
3.  A sample whose label is not in the sheet, and every run-only sample
    (inputs, which the sheet does not list), keeps its stored value and
    is listed in the report.

Only rows whose coordinates change are written. The script only reads;
it writes a .sql file for a human to apply.
"""

from __future__ import annotations

import argparse
import collections
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from noxdb.connection import close_pool, execute, init_pool  # noqa: E402
from noxdb.ip_runs import by_old_label, coords_for_old_name, load_plates  # noqa: E402

def resolve(db_rows, projects_of, plates):
    """Pair every database row with its plate from the sheet.

    Returns:
        ``(changes, kept, errors)``. *changes* lists
        ``(sample_id, name, old (IPR, IPRP), new (IPR, IPRP))`` for rows
        that move; *kept* lists ``(name, reason)`` for rows left as
        stored; *errors* lists rows a clashing label could not settle.
    """
    index = by_old_label(plates)
    changes, kept, errors = [], [], []
    for row in db_rows:
        name = row["sample_name"]
        if row["IPRP"] == "":
            kept.append((name, "run-only (input)"))
            continue
        found = coords_for_old_name(index, name, projects_of.get(row["sample_id"], set()))
        if not found:
            kept.append((name, f"R{row['IPR']}P{row['IPRP']} not in sheet"))
            continue
        if len(found) > 1:
            errors.append((name, found, sorted(projects_of.get(row["sample_id"], set()))))
            continue
        stored = (row["IPR"], row["IPRP"])
        if stored != found[0]:
            changes.append((row["sample_id"], name, stored, found[0]))
    return changes, kept, errors


def render_sql(changes) -> str:
    """Render the changes as one temporary-table join.

    Several plates swap labels (old R09P03 becomes R09P01 while old
    R09P06 becomes R09P03), so the rows are keyed by ``sample_id`` and
    moved in a single statement, never plate by plate.
    """
    values = ",\n".join(
        f"  ({sid}, '{new[0]}', '{new[1]}')" for sid, _name, _old, new in changes
    )
    return f"""-- Rewrite samples.IPR / samples.IPRP from the Overview of IP runs sheet.
-- Generated by scripts/set_ip_coords_from_overview.py — do not hand-edit.
--
-- Rows: {len(changes)}

USE ccr_metadata;

CREATE TEMPORARY TABLE _ip_coords (
    sample_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    IPR       VARCHAR(10) NOT NULL,
    IPRP      VARCHAR(10) NOT NULL
) ENGINE=InnoDB;

INSERT INTO _ip_coords (sample_id, IPR, IPRP) VALUES
{values};

START TRANSACTION;

UPDATE samples s
JOIN _ip_coords t ON t.sample_id = s.sample_id
SET s.IPR = t.IPR, s.IPRP = t.IPRP;

-- Must report 0.
SELECT COUNT(*) AS rows_not_moved
FROM samples s JOIN _ip_coords t ON t.sample_id = s.sample_id
WHERE s.IPR <> t.IPR OR s.IPRP <> t.IPRP;

COMMIT;

DROP TEMPORARY TABLE _ip_coords;
"""


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate the IPR/IPRP rewrite SQL from the IP runs sheet.",
    )
    ap.add_argument("sheet", type=Path,
                    help="'Overview of IP runs TV(Overview)' CSV export.")
    ap.add_argument("-o", "--out", type=Path,
                    default=Path("set_ip_coords_from_overview.sql"),
                    help="Where to write the generated SQL.")
    ap.add_argument("--report", action="store_true",
                    help="List every plate that moves and every row kept as stored.")
    args = ap.parse_args()

    if not args.sheet.is_file():
        print(f"ERROR: no such sheet: {args.sheet}", file=sys.stderr)
        return 2

    plates = load_plates(args.sheet)
    print(f"sheet: {len(plates)} plates")

    init_pool()
    try:
        db_rows = execute(
            "SELECT sample_id, sample_name, IPR, IPRP FROM samples ORDER BY sample_id"
        )
        links = execute(
            "SELECT ps.sample_id, p.project_name FROM project_samples ps "
            "JOIN projects p USING (project_id)"
        )
    finally:
        close_pool()
    print(f"database: {len(db_rows)} samples")

    projects_of: dict[int, set[str]] = collections.defaultdict(set)
    for link in links:
        projects_of[link["sample_id"]].add(link["project_name"])

    changes, kept, errors = resolve(db_rows, projects_of, plates)
    print(f"changed: {len(changes)}  kept as stored: {len(kept)}  "
          f"unsettled clashes: {len(errors)}")

    if args.report:
        moves = collections.Counter(
            (f"R{o[0]}P{o[1]}", f"R{n[0]}P{n[1]}") for _s, _n, o, n in changes
        )
        print("\nplates moved (stored -> sheet):")
        for (old, new), n in sorted(moves.items()):
            print(f"  {old} -> {new}  {n} rows")
        reasons = collections.Counter(reason for _name, reason in kept)
        print("\nkept as stored:")
        for reason, n in sorted(reasons.items()):
            print(f"  {reason}: {n} rows")
    if errors:
        print(f"\nERROR: {len(errors)} samples carry a clashing label no project "
              "settles; refusing to write a partial rewrite:", file=sys.stderr)
        for name, found, projects in errors[:20]:
            print(f"  {name} (plates {found}, projects {projects})", file=sys.stderr)
        return 1
    if not changes:
        print("nothing to change")
        return 0

    args.out.write_text(render_sql(changes), encoding="utf-8")
    print(f"\nwrote {args.out} ({len(changes)} rows)")
    print("apply with:")
    print(f"  mysql -u <user> -p ccr_metadata < {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
